"""
Script: generate_content_modular.py
Purpose: Generate PDF content in modular chunks (outline → chapters → pages)
Inputs: Topic name
Outputs: Complete markdown content built page-by-page
Author: AI-Assisted
Created: 2025-11-29
"""

import os
import sys
import json
from datetime import datetime


def generate_outline(topic, target_pages=25):
    """
    Generate a detailed outline for the guide.

    Args:
        topic: The topic to write about
        target_pages: Target number of pages (default 25)

    Returns:
        Dictionary with outline structure
    """
    print(f"[*] Generating outline for: {topic}")
    print(f"[*] Target length: {target_pages} pages")

    # For ChatGPT guide - this would be generated by AI in production
    outline = {
        "title": f"{topic.title()}: Complete Action Guide",
        "subtitle": "Get more done in less time with proven techniques",
        "target_pages": target_pages,
        "chapters": [
            {
                "number": 1,
                "title": "Getting Started: The Fundamentals",
                "pages": 3,
                "sections": [
                    "What makes a good prompt",
                    "The 4 elements every prompt needs",
                    "Common mistakes that waste time"
                ]
            },
            {
                "number": 2,
                "title": "The Prompt Engineering Framework",
                "pages": 4,
                "sections": [
                    "Role + Task + Context formula",
                    "Adding constraints for better output",
                    "Examples vs instructions",
                    "The iteration strategy"
                ]
            },
            {
                "number": 3,
                "title": "20 Practical Use Cases",
                "pages": 5,
                "sections": [
                    "Writing & Communication (5 uses)",
                    "Business & Productivity (5 uses)",
                    "Learning & Research (5 uses)",
                    "Creative & Problem-Solving (5 uses)"
                ]
            },
            {
                "number": 4,
                "title": "Advanced Techniques",
                "pages": 4,
                "sections": [
                    "Chain-of-thought prompting",
                    "Role-playing for better results",
                    "Multi-turn conversation strategies",
                    "Custom instructions setup"
                ]
            },
            {
                "number": 5,
                "title": "Daily Productivity System",
                "pages": 3,
                "sections": [
                    "Morning workflow (5-minute setup)",
                    "During-work best practices",
                    "Evening review routine",
                    "Building your prompt library"
                ]
            },
            {
                "number": 6,
                "title": "50 Ready-to-Use Prompts",
                "pages": 4,
                "sections": [
                    "Writing prompts (10)",
                    "Business prompts (10)",
                    "Learning prompts (10)",
                    "Productivity prompts (10)",
                    "Bonus prompts (10)"
                ]
            },
            {
                "number": 7,
                "title": "Quick Reference & Cheat Sheets",
                "pages": 2,
                "sections": [
                    "Pre-flight checklist",
                    "Prompt starters library",
                    "Troubleshooting guide"
                ]
            }
        ]
    }

    total_chapter_pages = sum(ch['pages'] for ch in outline['chapters'])
    print(f"[+] Outline created: {len(outline['chapters'])} chapters, {total_chapter_pages} pages")

    return outline


def generate_page_content(chapter_num, chapter_title, section_content, page_num_in_chapter):
    """
    Generate content for a single page.
    This is where you'd call Claude API in production.
    For now, returns structured template.
    """
    # This is a placeholder - in production this would be a Claude API call
    # with a prompt like: "Write 1 page of content for Chapter {chapter_num}: {section_content}"

    content_blocks = {
        # Chapter 1 content
        (1, 1): """## Chapter 1: Getting Started: The Fundamentals

### What Makes a Good Prompt

The difference between a mediocre ChatGPT response and a game-changing one comes down to your prompt. A good prompt is:

**Specific:** Don't say "help me write." Say "write a 200-word product description for eco-friendly water bottles targeting millennials."

**Contextual:** Give ChatGPT the background it needs. "I'm a small business owner" vs "I'm a Fortune 500 CMO" will get very different advice.

**Goal-oriented:** What do you want to accomplish? "I need to convince my team to adopt this tool" is clearer than "tell me about this tool."

**The 3-Second Test:** Can someone else read your prompt and understand exactly what you want? If not, ChatGPT won't either.

**Real Example:**

BAD: "Write about productivity"
GOOD: "Write 5 productivity tips for remote workers who struggle with distractions. Each tip should be actionable and take less than 5 minutes to implement."

The good prompt is 3x longer but gets 10x better results.""",

        (1, 2): """### The 4 Elements Every Prompt Needs

Think of prompts like cooking recipes. Miss an ingredient and the dish fails. Every effective prompt has these 4 elements:

**1. ROLE - Who should ChatGPT be?**
"Act as an experienced email marketer..."
"You are a supportive fitness coach..."
"Pretend you're a technical writer explaining to beginners..."

**2. TASK - What should it do?**
"Write a cold outreach email"
"Create a 4-week workout plan"
"Explain how APIs work"

**3. CONTEXT - What background does it need?**
"My target audience is SaaS founders"
"I'm a beginner with no equipment at home"
"I'm a designer who needs to understand development"

**4. FORMAT - How should it deliver?**
"Keep it under 100 words"
"Use bullet points only"
"Explain like I'm 12 years old"

**Formula in Action:**

"[ROLE] Act as a professional resume writer. [TASK] Review my resume and suggest 5 improvements. [CONTEXT] I'm applying for senior product manager roles at tech companies. [FORMAT] Give specific examples of what to change and why."

This formula works for ANY task.""",

        (1, 3): """### Common Mistakes That Waste Time

**Mistake #1: Being Too Vague**
"Help me with my business" → What business? What kind of help?

**Fix:** "I run a local bakery. Suggest 3 ways to increase weekend foot traffic without spending money on ads."

**Mistake #2: Accepting the First Response**
ChatGPT's first attempt is rarely its best. It's a starting point, not the finish line.

**Fix:** Use "Try again, but make it..." or "Improve this by adding..."

**Mistake #3: No Quality Control**
ChatGPT can be confidently wrong. Always verify facts and adapt tone to match your voice.

**Fix:** Treat output as a first draft. You add the final 20% that makes it yours.

**Mistake #4: Forgetting Context Carries**
In a conversation, ChatGPT remembers what you said. Use this.

**Bad:** Repeating all context in every message
**Good:** "Now do the same thing but for LinkedIn instead of email"

**Mistake #5: Not Saving What Works**
Found a great prompt? Save it. You'll use variations of good prompts hundreds of times.

**Fix:** Keep a simple text file of your best prompts organized by category (emails, brainstorming, analysis, etc.).

**Quick Win:** Next time ChatGPT gives you something close but not quite right, don't start over. Say "This is good but [specific issue]. Please revise." Saves 80% of the time.""",

        (2, 1): """## Chapter 2: The Prompt Engineering Framework

### Role + Task + Context Formula

This is the foundation. Master this and everything else becomes easier.

**ROLE: Who is ChatGPT in this conversation?**

Bad: Generic assistant
Good: Specific expert

Examples:
- "You are a direct response copywriter who specializes in email marketing"
- "Act as a patient JavaScript tutor teaching beginners"
- "You're a seasoned hiring manager reviewing resumes for tech startups"

**Why roles work:** ChatGPT has trained on content from millions of sources. When you assign a role, you're telling it which "knowledge pool" to draw from.

**TASK: What exactly should it do?**

Be verb-specific:
- Write, Analyze, Summarize, Explain, Create, Review, Suggest, Compare, Translate, Debug

Bad: "Do something with this data"
Good: "Analyze this sales data and identify the top 3 trends"

**CONTEXT: What background information matters?**

Think: Who, What, When, Where, Why
- Who is the audience?
- What's the goal?
- When will this be used?
- Where will it appear?
- Why does it matter?

**Example Breakdown:**

"[ROLE] You are an experienced product manager. [TASK] Write a one-pager proposing a new feature. [CONTEXT] The feature is dark mode for our mobile app. Our users are designers who work late hours. The one-pager will go to our CEO for budget approval. [FORMAT] Use bullet points and keep it to 300 words.""",

        (2, 2): """### Adding Constraints for Better Output

Constraints aren't limitations—they're creative catalysts. The right constraints make ChatGPT's output 10x more useful.

**Length Constraints:**
- "Write this in exactly 50 words"
- "Keep each section under 100 words"
- "Expand this to 500 words minimum"

**Tone Constraints:**
- "Use a conversational, friendly tone like you're talking to a friend"
- "Professional but approachable—think startup, not corporate"
- "Academic and formal with citations"

**Format Constraints:**
- "Use only bullet points, no paragraphs"
- "Structure as: Problem → Solution → Benefit"
- "Create a table with 3 columns: Feature, Benefit, Example"

**Audience Constraints:**
- "Write for complete beginners with no technical knowledge"
- "Target busy executives who skim content"
- "Explain to someone with 5 years experience who wants advanced techniques"

**Style Constraints:**
- "No jargon or corporate speak"
- "Use short sentences (max 15 words each)"
- "Include a metaphor or analogy in every section"

**Real Example:**

Without constraints: "Write about time management"

With constraints: "Write 5 time management tips in bullet points. Each tip should be under 30 words, actionable within 5 minutes, and include a specific example. Write for remote workers who struggle with distractions. Tone: direct and motivational."

**The Magic:** More constraints = less decision space = faster, better output. ChatGPT performs best when you narrow the possibilities.""",

        (2, 3): """### Examples vs Instructions

Should you show ChatGPT what you want (examples) or tell it (instructions)? Use both.

**When to Use Examples:**

Examples work best when you have a specific style, format, or pattern in mind.

"Write 3 headlines like these:
- '10-Minute Meals That Don't Taste Like Shortcuts'
- 'The Email Template That Gets 80% Response Rates'
- 'Why Smart People Make Dumb Money Mistakes'"

ChatGPT will match the pattern: specific number, benefit-driven, intriguing contradiction or claim.

**When to Use Instructions:**

Instructions work best for general direction without a fixed pattern.

"Write headlines that are:
- 10-12 words long
- Start with 'How' or 'Why'
- Focus on practical outcomes
- Avoid clickbait language"

**The Power Combo: Examples + Instructions**

"Write 5 social media captions similar to these examples:

Example 1: 'Your to-do list isn't the problem. Your priorities are. Here's how to fix it in 10 minutes.'

Example 2: 'Stop scheduling meetings. Start scheduling thinking time. Your future self will thank you.'

Follow this pattern:
- Start with a provocative statement
- Add a reframe or twist
- End with a simple action or benefit
- Keep under 25 words
- Use sentence fragments for impact"

**Pro Tip:** Give 2-3 examples minimum. One example is a data point. Three examples show a pattern. ChatGPT is excellent at pattern matching.""",

        (2, 4): """### The Iteration Strategy

Your first prompt won't be perfect. Neither will ChatGPT's first response. That's okay. Iteration is the real skill.

**The 3-Round Rule:**

**Round 1:** Get something on the page
"Write a 200-word product description for noise-canceling headphones"

**Round 2:** Refine what works
"This is good but too technical. Rewrite focusing on emotional benefits (focus, calm, productivity) rather than specs."

**Round 3:** Polish specific elements
"Perfect. Now make the opening sentence more punchy and add a call-to-action at the end."

**Iteration Commands That Work:**

- "Make this shorter" / "Expand this section"
- "Use simpler language—8th grade reading level"
- "Add more specific examples"
- "Change the tone to be more [casual/formal/urgent]"
- "Keep the structure but rewrite for [different audience]"
- "This is 80% there. The issue is [X]. Fix that."

**Building On Previous Responses:**

ChatGPT remembers your conversation. Use this.

You: "Write 5 blog post ideas about productivity"
ChatGPT: [provides 5 ideas]
You: "I like #2 and #4. Combine them into one post and write an outline"
ChatGPT: [creates outline]
You: "Great. Now write the introduction section in a conversational tone"

**Save Versions:**

When ChatGPT produces something good, ask for variations:
"Give me 3 different versions of this: one short and punchy, one detailed and thorough, one somewhere in between"

Pick the best or combine elements from each.""",

        (3, 1): """## Chapter 3: 20 Practical Use Cases

### Writing & Communication (5 Uses)

**Use Case 1: Email Drafting**

Stop staring at blank emails. Let ChatGPT draft them in 10 seconds.

Template: "Write a [type] email to [recipient] about [topic]. Tone: [style]. Length: [constraint]."

Example: "Write a follow-up email to a client who went dark after our proposal. Tone: friendly, not pushy. Ask if they need anything else to make a decision. Under 75 words."

**Use Case 2: Content Repurposing**

One piece of content becomes ten.

"Take this blog post and create:
- 5 LinkedIn posts (150 words each, hook in first line)
- 10 tweet-length insights
- An email newsletter version (300 words)
[Paste content]"

**Use Case 3: Difficult Conversations**

Practice tough messages before sending them.

"I need to tell my team a project is being canceled. Help me write a message that:
- Acknowledges their hard work
- Explains the business reason clearly
- Keeps morale up
- Offers next steps"

**Use Case 4: Writing Improvement**

Paste your draft, get instant feedback.

"Review this paragraph and suggest improvements. Focus on clarity, conciseness, and impact: [paste text]"

Or: "Rewrite this to be 50% shorter without losing key points: [paste text]"

**Use Case 5: Tone Adjustment**

Same message, different audiences.

"Rewrite this explanation three ways:
1. For executives (brief, ROI-focused)
2. For technical team (detailed, implementation-focused)
3. For customers (benefit-focused, jargon-free)

[Paste original]"

**Time Saved: 5-10 hours per week on writing and communication tasks.""",

        (3, 2): """### Business & Productivity (5 Uses)

**Use Case 6: Meeting Preparation**

Never walk into a meeting unprepared.

"I have a quarterly review with my manager tomorrow. Generate:
- 10 thoughtful questions about career growth and team direction
- 5 talking points about my accomplishments this quarter
- 3 areas where I could use more support"

**Use Case 7: Data Analysis**

Get insights from information overload.

"Here's our sales data from Q3 [paste data]. Analyze and tell me:
- Top 3 trends
- Biggest concerns or red flags
- 2 actionable recommendations"

**Use Case 8: Process Documentation**

Turn tribal knowledge into documented procedures.

"I need to document our customer onboarding process. Ask me questions about each step, then create a clear, step-by-step guide that anyone on the team could follow."

**Use Case 9: Strategic Planning**

Brainstorm and pressure-test ideas.

"I'm considering launching [product/service]. Help me think through:
- Who would buy this and why
- Main competitors and how we'd differentiate
- Potential roadblocks
- Quick way to validate demand before building"

**Use Case 10: Time Audits**

Find where your time actually goes.

"I'll paste my calendar from last week. Analyze how I spent my time and suggest:
- Time blocks that could be delegated
- Meetings that could be emails
- Better ways to batch similar tasks
- Where I should protect focus time"

**Time Saved: 3-7 hours per week on business planning and decision-making.**
    }

    # Return specific content if available, otherwise generate generic
    key = (chapter_num, page_num_in_chapter)
    if key in content_blocks:
        return content_blocks[key]
    else:
        # Generic template for pages we haven't written yet
        return f"""## Chapter {chapter_num}: {chapter_title}

### {section_content}

[Content for this page would be generated here]

This section covers: {section_content}

Key takeaways:
- Point 1 with specific example
- Point 2 with actionable advice
- Point 3 with real-world application

**Try This:** [Specific exercise or example prompt to practice]

**Common Question:** [FAQ related to this section]

**Pro Tip:** [Advanced insight or shortcut]
"""


def build_full_guide(topic, outline):
    """
    Build the complete guide page by page.
    """
    print(f"\n[*] Building full guide...")

    content_parts = []

    # Title page
    content_parts.append(f"""# {outline['title']}

*{outline['subtitle']}*

---

## What You'll Learn

This guide gives you everything you need to master {topic}:

""")

    # Add chapter summaries to intro
    for chapter in outline['chapters']:
        content_parts.append(f"**Chapter {chapter['number']}: {chapter['title']}** - {', '.join(chapter['sections'][:2])}\n")

    content_parts.append(f"""
**Total Reading Time:** ~{outline['target_pages']} minutes (1 page = 1 minute)

**Best Use:** Read once, then keep as reference. Each chapter is standalone.

---
""")

    # Generate each chapter page by page
    page_count = 1
    for chapter in outline['chapters']:
        print(f"[*] Generating Chapter {chapter['number']}: {chapter['title']} ({chapter['pages']} pages)")

        for page_in_chapter in range(1, chapter['pages'] + 1):
            section_idx = min(page_in_chapter - 1, len(chapter['sections']) - 1)
            section = chapter['sections'][section_idx]

            page_content = generate_page_content(
                chapter['number'],
                chapter['title'],
                section,
                page_in_chapter
            )

            content_parts.append(page_content + "\n\n---\n\n")
            page_count += 1

            print(f"  [+] Page {page_count - 1} generated")

    # Conclusion
    content_parts.append("""## Conclusion: Your Next Steps

You now have the framework, techniques, and prompts to use ChatGPT effectively.

**Today:** Pick ONE technique from this guide and use it 3 times.

**This Week:** Build your prompt library with your 10 most-used tasks.

**This Month:** Track time saved. Most people save 5-10 hours per week.

**Remember:** ChatGPT is a tool. The better your prompts, the better your results. Start simple, iterate often, and save what works.

---

*Thank you for reading. Now go put this into practice.*
""")

    full_content = "".join(content_parts)

    print(f"\n[+] Guide complete: ~{page_count} pages")

    return full_content


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_content_modular.py <topic>")
        print("\nExample:")
        print("  python generate_content_modular.py 'how to use chatgpt effectively'")
        sys.exit(1)

    topic = sys.argv[1]
    target_pages = int(sys.argv[2]) if len(sys.argv) > 2 else 25

    print("="*80)
    print(">>> MODULAR CONTENT GENERATION")
    print("="*80)

    # Step 1: Generate outline
    outline = generate_outline(topic, target_pages)

    # Step 2: Build guide page by page
    content = build_full_guide(topic, outline)

    # Step 3: Save to file
    topic_slug = topic.lower().replace(' ', '-')
    output_file = f'.tmp/content_{topic_slug}.md'

    os.makedirs('.tmp', exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"\n[+] Content saved to: {output_file}")
    print(f"[+] Ready to convert to PDF")

    return output_file


if __name__ == "__main__":
    main()
